import type { Metadata } from "next";
import { Be_Vietnam_Pro, Inter } from "next/font/google";
import "./globals.css";

const beVietnam = Be_Vietnam_Pro(
  {
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],

 });

export const metadata: Metadata = {
  title: "Pikup",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnam.className}>{children}</body>
    </html>
  );
}
